version: '3'
services:
  mongo: 
    image: mongo:6.0.3
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=kraikub
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=123456
    volumes:
      - ./db:/data/db

  redis:
    image: redis:7.0.5-alpine
    command: redis-server --requirepass @kraikub.redis
    restart: always
    ports:
      - '6379:6379'
    

